name: .NET

on:
  push:
    branches: ["master", "dev"]
    paths-ignore:
      - README.md      
      - .gitignore

  pull_request:
    branches: ["master", "dev"]
    paths-ignore:
      - README.md      
      - .gitignore
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        wiht:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release